eventbrite-like/config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users

  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

eventbrite-like/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

eventbrite-like/app/models/event.rb
class Event < ApplicationRecord

	belongs_to :creator, class_name: "User"

	has_and_belongs_to_many :attendees, class_name: "User"

end

eventbrite-like/app/models/user.rb
class User < ApplicationRecord

	has_many :created_events, class_name: "Event", foreign_key: "creator_id"

	has_and_belongs_to_many :participated_events, class_name: "Event"

end

eventbrite-like/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

eventbrite-like/app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index

		@event = Event.all

	end

	def new

		@event = Event.new

	end

	def create

		@event = Event.create(event_params)

		session[:current_user_id] = @user.id

		redirect_to show_event_path

	end

	def show

		@event = Event.find(params[:id])

	end

	def edit

		@event = Event.find(params[:id])

		@attendees = Attendees.all

	end

	def update

		@event = Event.find(params[:id])

		@event.update(event_params)

		redirect_to show_event_path

	end

	def destroy

		@event = Event.find(params[:id])

		@event.destroy

		redirect_to events_path

	end

	private

	def event_params

		params.require(:event).permit(:description, :date, :place)

	end
end

eventbrite-like/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index

		@user = User.all

	end

	def new

		@user = User.new

	end

	def create

		@user = User.create(user_params)

		session[:current_user_id] = @user.id

		redirect_to user_path(@user.id)

	end

	def show

		@user = User.find(params[:id])

		@created_events = Created_events.all

		@participated_events = Participated_events.all

	end

	def edit

		@user = User.find(params[:id])

	end

	def update

		@user = User.find(params[:id])

		@user.update(user_params)

		redirect_to show_user_path

	end

	def destroy

		@user = User.find(params[:id])

		@user.destroy

		redirect_to users_path

	end

	private

	def user_params

		params.require(:user).permit(:name)

	end

end

eventbrite-like/app/helpers/application_helper.rb
module ApplicationHelper
end

eventbrite-like/app/helpers/events_helper.rb
module EventsHelper
end

eventbrite-like/app/helpers/users_helper.rb
module UsersHelper
end

eventbrite-like/app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

eventbrite-like/app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

<% @event.each do |event| %>

	<p><%= event.description %></p>

	<p><%= event.date %></p>

	<p><%= event.place %></p>

	<a href="<%= event_path(event.id) %>" >Lire l'event</a>

<% end %>

eventbrite-like/app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>


<%= form_for @event do |f| %>

   <div>

   	<label>description</label>

   	<%= f.text_area :description %>

   </div>

   <div>

   <label>date</label>

   	<%= f.text_field :date %>

   </div>

   <div>

   <label>place</label>

   	<%= f.text_field :place %>

   </div>

   <div>

   	<button type="submit" >Créer</button>

   </div>

<% end %>

eventbrite-like/app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

<p><%= @event.description %></p>

<p><%= @event.date %></p>

<p><%= @event.place %></p>

<a href="<%= user_url %>" >Lire son profil</a>

<% @attendees.each do |attendees| %>

	<p><%= attendees.name %></p>

<% end %>

eventbrite-like/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

eventbrite-like/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

eventbrite-like/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<a href="<%= new_user_path %>" >Créer un profil</a>

eventbrite-like/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for @user do |f| %>

   <div>

   	<label>name</label>

   	<%= f.text_field :name %>

   </div>

   <div>

   	<button type="submit" >Créer</button>

   </div>

<% end %>

eventbrite-like/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<h1>Ton profil !</h1>

<p>Ton name : <%= @user.name %></p>

<a href="<%= new_event_path %>" >New event</a>

<a href="<%= users_path %>" >Index user</a>

<%= link_to 'Clique pour supprimer ton profil', @moussaillon, method: :delete %>

<h2>Tes Events !</h2>

<% @created_events.each do |created_events| %>

	<p><%= created_events.description %></p>

	<p><%= created_events.date %></p>

	<p><%= created_events.place %></p>

	<a href="<%= event_path(event.id) %>" >Lire l'event</a>

<% end %>

<h2>Les Events auquel tu participe !</h2>

<% @participated_events.each do |participated_events| %>

	<p><%= participated_events.description %></p>

	<p><%= participated_events.date %></p>

	<p><%= participated_events.place %></p>

	<a href="<%= event_path(event.id) %>" >Lire l'event</a>

<% end %>